services:
  backend:
    image: yapi-backend:latest
    ports:
      - 8080:8080
  database:
    image: postgres:14.12
    restart: on-failure
    container_name: y-database
    environment:
        POSTGRES_USER: y-dba
        POSTGRES_PASSWORD: V3rySecret
        POSTGRES_DB: yDB
    ports:
      - 5432:5432
